package ar.edu.unlam.pb1.interfaz.enums;

public enum MenuPrincipal {
	AGREGAR_PRODUCTO, 
	AGREGAR_STOCK_A_PRODUCTO, 
	INCREMENTAR_COSTO_DE_PRODUCTO_EN_PORCENTAJE,
	MOSTRAR_PRODUCTOS_POR_SECCION,
	MOSTRAR_PROMEDIO_DE_PRECIO_VENTA_DE_PRODUCTOS_POR_SECCION_CON_O_SIN_IVA, 
	SALIR
}
